### ISSUE TITLE
The task is replacing all single quotes with double quotes in HTML

### ISSUE THREAD

**Issue by sean256** [sparanoid/grunt-assets-inline#26] opened 2017-08-27 01:28 UTC
This:

`onclick='openWindow("windowPersonalNotes",event)'`

becomes

`onclick="openWindow("windowPersonalNotes",event)"`

Which of course breaks stuff.

**Comment by sparanoid** [comment] 2018-08-15 10:40
Hi @sean256 I don't know if you're still using this plugin but this should now be fixed via https://github.com/sparanoid/grunt-assets-inline/commit/369e7a8f5f0ff10200d64a493d84ec0d96f4ffc5

It was likely a bug caused by cheerio. I've switched from cheerio to jsdom and it seems to be working fine:

Before:
```html
<p onclick='alert("test")'>Hello world! This is a test.</p>
```

After:
```html
<p onclick="alert(&quot;test&quot;)">Hello world! This is a test.</p>
```

**Closed as completed by sparanoid** 2018-08-15 10:40 UTC
Labels: bug
